onboarding = false

[worktrees]
directory = "~/.local/worktrees"

[theme]
name = "catppuccin"
auto_switch = false

[ui]
show_agent_labels_on_pane_borders = false
agent_panel_sort = "spaces"

[ui.toast]
delivery = "terminal"

[[keys.command]]
key = "ctrl+h"
type = "plugin_action"
command = "herdr-nvim-nav.left"

[[keys.command]]
key = "ctrl+j"
type = "plugin_action"
command = "herdr-nvim-nav.down"

[[keys.command]]
key = "ctrl+k"
type = "plugin_action"
command = "herdr-nvim-nav.up"

[[keys.command]]
key = "ctrl+l"
type = "plugin_action"
command = "herdr-nvim-nav.right"
