[tools]
bat = "latest"
eza = "latest"
fd = "latest"
gh = "latest"
markdownlint-cli2 = "latest"
neovim = "latest"
ripgrep = "latest"
zoxide = "latest"

[shell_alias]
less = "bat"
cat = "bat -pP"
cd = "z"

l = "eza -l --icons --git -a"
lt = "eza --tree --level=2 --long --icons --git"
ltree = "eza --tree --level=2  --icons --git"

v = "nvim"
vi = "nvim"

[bootstrap.repos]
"~/.dotfiles" = { url = "https://github.com/hdweiss/dotfiles.git", ref = "main" }
"~/.config/nvim" = { url = "https://github.com/LazyVim/starter", ref = "main" }

[dotfiles]
"~/.bashrc/activate" = { block = 'eval "$(~/.local/bin/mise activate bash)"' }
"~/.bashrc/zoxide" = { block = 'eval "$(zoxide init bash)"' }
"~/.config/markdownlint-cli2/config.jsonc" = {}
"~/.config/mise" = { mode = "symlink-each" }
"~/.config/nvim/lazyvim.json" = {}
"~/.config/nvim/lua/plugins/lint.lua" = {}

